### ISSUE TITLE
When did you know that you wanted to have a career in software?

### ISSUE THREAD

**Issue by swanson** [r00k/AMA#13]

**Comment by r00k** [comment]
I was very lucky.

My dad brought home an IBM XT 286 when I was ~8.

It looked like this:

![ibm](https://cloud.githubusercontent.com/assets/46677/6654139/e8f0b8c8-caa8-11e4-9b1a-39876882c9a8.jpg)

I remember spending a full day trying to figure out the `dir` command. I knew there had to be _some_ command that would show you all your files, but had no idea what it was.

Finally, my dad got home and I asked him about it over dinner.

The first time I typed `dir` and saw the dozens of programs I could execute, my life changed. I've wanted to work in software ever since.
