### ISSUE TITLE
Diversity Statistics for Thoughtbot

### ISSUE THREAD

**Issue by cllns** [r00k/AMA#49]
Can Thoughtbot publish diversity statistics?

A bunch of large tech companies have released their [diversity](http://www.techrepublic.com/article/diversity-stats-10-tech-companies-that-have-come-clean/) [statistics](https://gigaom.com/2014/08/21/eight-charts-that-put-tech-companies-diversity-stats-into-perspective/#overview), and I think more organizations should.

I was involved in a  [twitter conversation](https://twitter.com/seancllns/status/606221109277687808) with @kylefiedler about this, in response to someone who was concerned about the lack of women in leadership roles. Separately, @alejandraluaces [also raised similar concerns](https://twitter.com/alejandraluaces/status/605383903973502976).

I was thrilled to hear @cpytel address the need for underrepresented groups in management, at 52:00 in the [most recent Giant Robots podcast](http://giantrobots.fm/153).

The reason I'm bothering to ask is that Thoughtbot is one of the most forward-thinking and transparent companies I've encountered. It seems like the right move for y'all, in my opinion :)

**Comment by alejandraluaces** [comment]
The first step in getting better is admitting that you have a problem... Which, of course, includes enlisting the help of our gracious tech community, not just leaving your e-mail address in a Twitter thread. Since Thoughtbot doesn't seem to have the numbers internally to reflect any demographic they'd be claiming to want to attract, it seems they need all the help they can get.  Kyle did mention being "cognizant" about the issue.. Not enough, sorry.  ¯_(ツ)_/¯ 

Publishing diversity statistics seems like a good first move.

An aside: some of the language in the podcast rubbed me the wrong way. What does "actual" minority mean? Why did Chad begin to say (but quickly corrected himself) he'd have to "lower the bar" to find minorities to move into leadership positions?

**Comment by cpytel** [comment]
Hi @alejandraluaces. Sorry, the word "actual" may have been poorly chosen on the fly, but we were talking about the blog post being about designers being a minority at thoughtbot.  What I meant by "actual" was non-role-based (designer) minorities and instead things like gender, race, etc.

Regarding what you thought may have I started to say and then corrected myself, I'm sorry, I'm not sure what you're referring to. There may be a misunderstanding.

I agree that being aware of the problem is not enough. We've done quite a bit about this internally, and we can do even more. Things like diversity statistics are an additional thing we could do, and I hope to do that over the next several months.

**Comment by alejandraluaces** [comment]
52:33: "Same thing applies, though. You don't want to just take people and **lower the––**, like, just pluck people up and say, "We need to have so-and-so on the management team," and that absence becomes more important than finding, you know, having someone who actually deserves to be in that position."

Maybe a misunderstanding. Maybe not.

**Comment by alejandraluaces** [comment]
At any rate, I would suggest (take with a grain of salt) having non-white community members help you with your diversity efforts. I'm sure you can understand that a diversity thinktank rife with caucasian men is just about equivalent to [all-male panels](http://allmalepanels.tumblr.com/) about women.

**Comment by alejandraluaces** [comment]
I have much respect for Thoughtbot. No hard feelings. Eagerly awaiting the progress you mention in these next few months.

**Comment by cpytel** [comment]
Thank you for clarifying. I see what you mean now, I did not think I corrected myself there, so the misunderstanding about what you were referring to was mine. I think we can assume I actually said the word I left out "bar".

I do believe that we do not simply want to fill positions with unqualified people simply to fill them. Instead, I believe that I should be quickly and proactively working to make more people qualified for those positions, as well as proactively seeking out those who are.

**Comment by cpytel** [comment]
> At any rate, I would suggest (take with a grain of salt) having non-white community members help you with your diversity efforts. I'm sure you can understand that a diversity thinktank rife with caucasian men is just about equivalent to all-male panels about women.

I agree.

**Comment by alejandraluaces** [comment]
:+1:

**Comment by r00k** [comment]
Thanks for the question!

Quoting Chad's response from above: "Things like diversity statistics are an additional thing we could do, and I hope to do that over the next several months."
