### ISSUE TITLE
How do I gain confidence in my skills as a web developer?

### ISSUE THREAD

**Issue by maxcodes** [r00k/AMA#7]
As a self taught, I usually struggle proving to myself and to other people that I know my stuff. Also, how do I know I'm improving?

**Comment by r00k** [comment]
First off, all programmers are self-taught. 

Even if you sit in a class with someone who explains how to build a Rails app, you've still got to struggle on your own to actually acquire the knowledge and make it usable.

Don't discount yourself for being self-taught. Say it proudly!

As for detecting progress: look at your old projects. Would you do them differently now? Congrats! You're...well, changing at least. That changing is almost certainly improving, since I don't think I've met anyone who kept writing code but got worse over time. :)

**Comment by r00k** [comment]
Also, if you struggle to accept your own abilities in general, consider a bit of therapy. Just a little can work wonders. It's done some great things for me in the past.

We've all got issues to work on. Therapy is a great format for putting in the work.

**Comment by maxcodes** [comment]
What kind of therapy do you mean? Also, at what point in time did you take your sessions? Thanks for doing this AMA!
