### ISSUE TITLE
Why is your name R00k?

### ISSUE THREAD

**Issue by indiesquidge** [r00k/AMA#9]

**Comment by r00k** [comment]
Hah!

When I was 10-ish I was really into chess. That was about the time I had to pick my first internet handle.

Rook was already taken, so I grabbed r00k and have been using it ever since.

I'm actually not a huge fan of it anymore, and have been thinking about just switching to something boring like benorenstein on all services.

**Comment by indiesquidge** [comment]
That's about the same situation as I am in. At least your's people can pronounce; mine isn't even coherent.

You can't change it now! Own it!
